name: Generate Predictions and Graphs

on: push
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  get_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'web_app'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: pip install -r requirements.txt 
      - run: python github_action.py
