name: Generate Predictions and Graphs

on: push
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  get_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'web_app'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: pip install -r requirements.txt 
      - run: python github_action.py
      - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git config --global user.name "github-actions"
      - run: git commit -a -m "Automated Commit"
      - run: git push origin web_app
